input_paths:
  - dir: "./a_folder"
    number_of_days: 3
    pattern: "*.csv"

  - dir: "./b_folder"
    number_of_days: 5
    pattern: "b_*.csv"

  - dir: "./c_folder"
    number_of_days: 9
    pattern: "*01*.csv"

  - dir: "./d_folder"
    number_of_days: 4
    pattern: "d_2025011*.csv"

log_file:
    path: "./logs"